### ISSUE TITLE
No setup or pyprojects file

### ISSUE THREAD

**Issue by fdev31** [johannesnoordanus/svg2gcode#1]
Hi,
I installed your code via pypi and had few issues with it.
After 1 or 2 lines patches It's the most useful tool for me now.
I see your related python packages aren't using any distribution/ setup file, they are very "barebone", is it intentional and would you accept contributions to make it "standard" python packages ? (I'm wondering how you push to pypi without this actually...)
I didn't test the HEAD yet but in the distribution there is an issue with cuttingpower which expects an int while it is a float...
Also the images didn't work out of the box for me, but I have more work todo for the "fix" I did (which is just working for me now but doesn't fix everything) so I'm not contributing it yet.
Anyway, thank you a lot for those projects!

**Comment by johannesnoordanus** [comment]
Hi Fabien,
I’ll look at the float/int problem you mention and fix it (when needed).
Images work for me, and I tested several scenario's. If you indicate the problem you encounter I’ll look at it.
The latest release (HEAD) fixes a viewbox problem I encountered when generation .svg files from OpenSCAD.
I distribute to pypi using _Flit_ . This is indeed a barebones solution. As far as I know, no setup file is needed for a pure (100%) Python package. No special installation/compilation is needed after all.
What additional benefit would a setup file have, except for complication things?
I am glad the tool is useful to you!

Regards,
Johannes

**Comment by fdev31** [comment]
Hi Johannes,
I'm not sure which library is different in your environment, here the linked images are not supported at all (unless I miss something in the code) and the inline (base64) ones throw such error:
```
cannot identify image file <_io.BytesIO object at 0x7f260f5ae660>
```
I plan to have a look at this one (I only have a fix for linked images at the moment) since you don't experience the same behavior. Maybe opening a separate bug ticket is worth it in case we need to discuss version dependencies etc... (looks like something broke compatibility, I'm running archlinux so I have "latest" versions of everything).

I didn't know Flit, I'll have a look. I believe the more "complicated" (now I'm using poetry, it's very very simple) ways have a few advantages:

- clear and controlled dependencies & package "metadata"
- ease of development for contributors (`pip install -e .`)

but maybe this is also achieved by your solution, it's just not clear for me yet how to deal with it without manual copying files etc... I like to work directly on the files from the git repository, which is easily done with pip.
I see your projects aren't supported at all by pip if not fetching from pypi, hence can't be installed in "editable mode" (files stay in place).
I believe this is a big stop for many casual contributors which are used to a simple workflow that always works.

So it makes things a bit more "complicated" once (when you write the pyproject file) but then it's easier for everybody...

One more thing, but it looks like your version (I didn't check the original) strips the items which are out of the "cutting zone" (aka svg viewport). Given how laser engravers work it's a bit a pitty, preventing people from having a centered origin (vs bottom left corner) - which can be VERY useful in some cases.

I guess this can be worked around by adding some new parameter like "--centered" and applying offets... but being able to have the origin at the center would really be useful :)

Edit: had a look at Flit, pretty nice indeed, but it's just a way to generate the pyprojects file... can you add it to the project instead of keeping it locally ? Else it forces people to install flit to easily work with this...  on the other hand, it looks like a good solution for trivial packages only requiring "any python version", but if you have 3rd party dependencies it's not managed at all... isn't it ?

**Comment by johannesnoordanus** [comment]
`cannot identify image file <_io.BytesIO object at 0x7f260f5ae660>`
Images should be included (inline) and of  type base64 (you can check that within the .svg file. 
I did some tests using _.png_ and _.jpg_ file formats, but others should work also (because of build in library support) but I did not test that.
I updated the README to reflect that.

I use Manjaro linux (latest version), which is based on archlinux, so that should be comparable.
I just installed the latest version of svg2gcode in a separate environment and did a test on a 'complicated' .svg and everything works fine.
(I also ran it on the Mac and this works fine: the output is binary compatible with that of linux Manjaro (Intel vs. ARM64)) 
Which software do you use to produce the .svg files? Because that could make a difference in the way files are included.

I fixed the type issue (argument _cuttingpower_ is now type float).

I added _pyproject.toml_ (which includes dependencies) and _HOWTOBUILD.md_ to the project. The _.toml_ file is generic for other types of install I read (see _HOWTOBUILD.md_ ).

Everything that is visible (in view) within the .svg file (when you save it) should be reproduced within the gcode files.
Point is that laser cutters use a lower left corner for the origin (0,0) and svg2gcode translates the .svg to start at this origin.

**Comment by fdev31** [comment]
Great !!
I'm using inkscape (too?), but figured there is something fishing related to the *display* settings, which doesn't make sense. I'll try again in case it was a pebcak. Anyway, I often use "linked" images and support is trivial, I'll be happy to open a feature request bug & propose a pull request unless you are faster than me ;)
About the visibility, do you mean negative coordinates aren't supported in laser engraver ? I'm coming from the 3D printing world and I assumed relative coordinates are also possible... so negative coordinates should be... in case it's really not an option, do you have some ideas to work around the problem and be able to "center" an object like a target instead of guessing the perfect bottom/left corner and eyeball the margin ? If this can be included in the software it would be awesome!
On top of this, it would be useful (I think, tell me if I'm wrong) to configure the minimum power too.
If I'm thinking even more, being able to specify the minimum value (speed + power) vs max value (speed + power) may enable the best results rendering images ? Finding the perfect line between min and max... maybe it's not linear, I have very little idea about that and don't think it's linear but applying different curves and checking results empirically can be efficient enough... ?
Anyway, I'm very happy with this project and it *really* fits my needs so far with the little comments I make :)
Thanks again for your time.

**Comment by fdev31** [comment]
Anyway, the original subject can be closed as far as I understand.

**Comment by johannesnoordanus** [comment]
It was my intention to support linked files also, so if you implemented that a pull request is fine by me.
Allow me some time to evaluate it though!
(I am currently busy updating `grblhud` to include Zaxis probes and work offsets (so the bit can be placed exactly on top of an object to be CNC’d) and several other things).

Laser engravers (cutters) support negative coordinates because grbl/gcode does. It is a matter of choice of course where you zero your X Y axis (and place your laser head). I guess the reason - for me - to use ‘positive’ coordinates is that images files (representations) are easily represented as a two dimensional array (having positive indices), also programs like Inkscape have positive coordinates as ‘default’. Also the laser engraver/cutter I have has axes markings starting at (0,0) to (400,400) (or so). So I defined a reference point (always) at left bottom.
But, as you point out, that does not need to be the case.
A bit too rigid thinking on my side I guess. I think maybe let the origin be defined by the user and not translate the left most, bottom most coordinates to (0,0)?
So maybe an option to set the origin, otherwise let it be defined by the SVG file.
I have to look into this to see if my code supports this … 

You ask about setting the laser head on a reference point.
A way to place the laser at a reference point is to turn it on (G0 X0 Y0; M3; S1; make sure G0 does not hit anything and the laser is on lowest power!) and place it by hand exactly at a marking on the object you are engraving (cutting). If x/y-axis alignment is needed you can laser the boundingbox (svg2gcode writes that to the gcode file it emits) with laser set to 1. You can repeat this and shift the object below until it is aligned.

It is also possible to jog (or by using gcode commands) to the marking (laser on 1) and subsequently shift the work coordinates of the laser machine to make this the new origin (G92 X0 Y0 I think)

This all is easy  to do using grblhud.

Your remarks about image engraving are spot on. A minimum setting is a good idea. I will look at that.
I experimented a lot with images and it is essential to turn up the contrast as much as possible using photo edit software. Maybe some software allows for a non linear contrast change!
The image rendering software I wrote applies a linear ‘formula’ but that can be made pluggable.
My experience is that above a certain laser intensity wood burns black and intensities higher than that does not show. That is why you can set the maximum laser intensity. A minimum intensity makes sense because only at a certain intensity wood burns (so intensity levels below that do not show).
I created test images with a linear intensity difference in several directions and ‘printed’ them. I based the cutoff laser intensity I used on this. I also concluded that intensity levels seemed fairly linear until the maximum. I also concluded that the dynamic range of the printed image is relatively low (300) compared to that of the original image.
The calibration depends of cause on the type of wood (hard, soft, color) and the laser head used.
I testend two laser heads and the one with low(er) power produced much beter images.
But, long story short: I produced very good images using this software. Better than most and as good as the best images I have seen online.
Note that the image software takes movement precision into account (by never using speed G0 code and always using a steady pace reversing at the edges).

**Comment by fdev31** [comment]
I use the laser in standalone mode now, mine have an ESP32+ small touch display where I can run things directly.
I'll be interested later for some automation eventually, but since it's not like a 3D printer but you have to physically put something on the "bed" I'm not too much in hurry for that.
Original images are better if they have a high contrast, but there are some tricks to make them more contrasted if they are not... then what I do which I'm quite happy with so far, with fixed speed & power (depending on the material) is to print some kind of ruler with a gradient under it.
I take the approximate position of the first "fully dark" and "fully white" zones in the gradient and then I make my images use this exact range as min and max (so they show very low contrast on the computer).
I'm losing some dynamic range this way, even though not very noticeable since burning material also have a low dynamic range in general... but being able to set "min" and "max" power would solve the loss of information.

I'm going to do a pull request for the linked files support... 
And was wondering why `--cuttingpower` uses a ratio and `--imagepower` an absolute value ?
Using absolute values for both would allow dropping the support for `--maxlaserpower` and simplify the CLI...
