### ISSUE TITLE
[Feature request] fill shapes

### ISSUE THREAD

**Issue by fdev31** [johannesnoordanus/svg2gcode#3]
Today it seems that shapes are only for cutting and inline images only for engraving.
One workaround is to use inkscape to export a rasterized image and import it in the document with matching positions.
It would be great to have this as an option, even if requiring inkscape as a dependency.

**Comment by johannesnoordanus** [comment]
True. But you could draw shapes (lines) with low laser power.
But I understand what you mean.
This requires a significant update because extensive 'rendering' has to be done. Line endpoints (joins), color, thickness and shape infill (color) has to be considered.
This can be done of course (Inkscape does it etc.).

One workaround I use is to let Inkscape (for example) export the whole document (.svg) as an raster image - a png for example - and use image2gcode to produce the engraving.

This works perfectly fine, even for text (fonts) and very fine detail!

**Comment by fdev31** [comment]
Yes, I do it using svg2gcode directly by working the original SVG to contain "double information" (for the outline and for the "_image" rendering).

This could also be done incrementally:
- making the feature using inkscape command line (so this feature would have additional dependency)
- (optionally) reworking it until similar  can be made with built-in code - but is it really worth it ? Most people will have inkscape I guess (or can install it) if they really want this feature ;)

**Comment by johannesnoordanus** [comment]
I am not sure I follow. You can combine the gcode files, the _image and non image one to one gcode file and print that in one go.
Why (and how) would you want to combine .svg files?

What I meant was to make one .svg document (via Inkscape for example) containing the outline and the image and write that out as a .png (one image containing all info). This png file can be printed directly via image2gcode. (It can of course be imported by Inkscape and printed via svg2gcode, but why would you? image2gcode uses the same engine as svg2gcode.)

**Comment by fdev31** [comment]
The answer is simple: to avoid extra manual steps.
If I understand the method using svg2gcode and image2gcode  (both using svgToGcode or something) I see a problem, beside two commands (+ edition to make it one gcode, indeed an option can be interesting for images, I use low power for borders) : the image2gcode will not have any offset, while the original svg drawing could be misaligned / needs to be aligned perfectly in the editor.

With the 2nd part, I understood you just use image2gcode, but here I use a low power "cut" for a nice finish of the outlines...

**Comment by johannesnoordanus** [comment]
> Today it seems that shapes are only for cutting and inline images only for engraving.
> One workaround is to use inkscape to export a rasterized image and import it in the document with matching positions.
> It would be great to have this as an option, even if requiring inkscape as a dependency.

I have a few ideas how to get shapes (paths) to fill and have stroke. Currently fill and stroke info is not added to the curve objects that represent paths. Also all path are lumped together which makes it difficult to apply specific properties. So the code has to be updated for that. Rendering 'stroke' comes down to shifting lines around the centreline (line part) at a multiple of 'pixelsize' (until half stroke width is reached); rendering 'fill' is similar to rendering 'stroke' until the center of the path is reached. Of course 'fill' and 'stroke' use the color set for it.
Color patterns and stripes etc, will take additional steps to implement.

**Comment by fdev31** [comment]
I stumbled upon https://github.com/pjpscriv/py-svg2gcode/ - it could be good maybe to share efforts ?
Unrelated to this topic (it would be great to reach you on discord or similar for off-topic discussions btw), I worked on an halftone converter recently and start to be happy with the result while keeping a low code complexity. I'll make some engraving tests first (I couldn't use it a lot recently) but if I can conclude with something really good, would you be interested in a pull request ? I couldn't find a simple tool to do it, so I think it can be a great addition (behind an optional cmdline flag).
For this to work, I would need to work on a surface which have the "optimal dpi" (given the provided pixelsize) - if you can advice about it you are very welcome to do so ;)

**Comment by johannesnoordanus** [comment]
> I stumbled upon https://github.com/pjpscriv/py-svg2gcode/ - it could be good maybe to share efforts ?

Interesting, a bezier conversion (svg2gcode uses line segments, from a path conversion done by Inkscape), but I think line width is not included. I'll do some tests.

> Unrelated to this topic (it would be great to reach you on discord or similar for off-topic discussions btw), I worked on an halftone converter recently and start to be happy with the result while keeping a low code complexity. I'll make some engraving tests first (I couldn't use it a lot recently) but if I can conclude with something really good, would you be interested in a pull request ? I couldn't find a simple tool to do it, so I think it can be a great addition (behind an optional cmdline flag).
> For this to work, I would need to work on a surface which have the "optimal dpi" (given the provided pixelsize) - if you can advice about it you are very welcome to do so ;)

Build in halftoning is a good idea, because it should be done on the image right before it is converted (no resizing after this). Option --showimage (of svg2gcode) can show this halftone conversion (it already shows image resize) right before a direct pixel translation to the gcode image. This makes the halftone effect visible as is and the conversion predictable.
So the right dpi is determined by the pixelsize; the image is resized accordingly by svg2gcode, directly after this step halftone conversion takes place (the image keeps its pixelrate) after which conversion to gcode starts.

So, I think we could incorporate your code, but I might need some time to evaluate. I also have several 'projects' running at the same time, so things are a bit intermittent.

I experimented a bit using Inkscape making halftone effects (several very short youtube clips showing that). I really like the output (great results), so it is an option to create (let people create) halftoning via Inkscape and save the image at the right dpi (for the intended pixelsize) and using image2gcode to convert.

**Comment by fdev31** [comment]
Halftone directly in inkscape ? I made this https://github.com/fdev31/firedot which works really good with image2gcode !

**Comment by johannesnoordanus** [comment]
> Halftone directly in inkscape ? I made this https://github.com/fdev31/firedot which works really good with image2gcode !

That looks really good! Nice work.

**Comment by johannesnoordanus** [comment]
> Today it seems that shapes are only for cutting and inline images only for engraving.
> One workaround is to use inkscape to export a rasterized image and import it in the document with matching positions.
> It would be great to have this as an option, even if requiring inkscape as a dependency.

I am busy finalising my 'Sinterklaas' update.
It supports 'stroke' color and stroke width of .svg *path* attributes.
This means it is possible to 'print' fonts and objects having a border (color).
It is even possible to use alpha channel now.

My followup 'Christmas' update will add support for the 'fill' attribute of *path* objects.

The above updates (and all other functionality) are not dependent on Inkscape, they will work for standard *.svg*.

**Comment by johannesnoordanus** [comment]
The *Sinterklaas* update version 3.0.0 is available now:
  ```pip install -U svg2gcode```

**Comment by johannesnoordanus** [comment]
Added evenodd fill. Latest version has some fixes and support for opacity (alpha channel).
Now available on PyPi.
Note that I updated the gcode viewer 'gcode2image' to version 2.4.0 which has support for multiple writes. So you can see colors (gray levels) and the effect (darkening) of repeated writes.
