### ISSUE TITLE
[Feature request] more flexible coordinate system

### ISSUE THREAD

**Issue by fdev31** [johannesnoordanus/svg2gcode#4]
I wish there was some options such as `--crop` that would make the origin match the most left and bottom coordinates.
Another option such as `--origin` could allow providing either some `x,y` coordinates or `"center"` which would make the origin at the center of the bounding box of the content in the svg document.

**Comment by johannesnoordanus** [comment]
Good points. I will look into this.

**Comment by johannesnoordanus** [comment]
Added option --origin to allow for an offset delta (to the origin (0,0) of the .svg document)
The view box of the svg document is leading i.e. the document determines the origin (as it should).
But now, you can shift it.
This covers this request I think.

**Comment by fdev31** [comment]
My main concern is to be able to center the origin... so I would say with this option as is, it's a bit tedious...

**Comment by johannesnoordanus** [comment]
This is a bit more generic. Bbox info (within the .gc file) might help. But I see your point.
Problem is that bbox calculation is while parsing the SVG, so that is available at the end.
Transformations have to be set at the start.
So I need 2 passes then.
 
Note that default (without using --origin) the origin is at left bottom (like your --crop option).

I added something you didn't request: option --scale.

**Comment by johannesnoordanus** [comment]
Updated file header info to contain the ... 'center'!
You can use --origin with this (negated values) to set the origin at the center.

**Comment by johannesnoordanus** [comment]
I think this request is closed. You agree?

**Comment by fdev31** [comment]
I really wanted a center option but maybe it's an unusual workflow. I can
work around it and your changes will help if I need it again. So ok to
close.

**Comment by johannesnoordanus** [comment]
Ok, but you did see that it is possible to set the origin at the center (you only need 2 runs)?
