### ISSUE TITLE
[improvement] do not move over unneeded zones when drawing images

### ISSUE THREAD

**Issue by fdev31** [johannesnoordanus/svg2gcode#5]
When rendering an image it looks like:

- white lines (not using the laser) are still moved over
- line doesn't start or stop when needed but always going over the full "bitmap" zone area

Optimizing this would allow greater engraving speed.

Another optimization that would be awesome, so called *flood fill* technique as far as I understood:

- detect every island containing zones to burn
- draw each zone as a separate image to draw
- ultimately, draw the image using "flood fill" algorithm instead of a rectangular "scan"
  - for instance, a thick circle will be drawn by quick tiny lines only (the thickness of the circle) and the laser head will have a global "slow" circular movement during the print. Instead of the "from top to bottom" current pattern.

**Comment by johannesnoordanus** [comment]
Good points.
That is a bit of a challenge.
Note that I made the current code as simple and compact as possible.
This means fewer possible errors and code that is easily to understand and maintain.
Also, I reduced speed changes to minimal because of possible machine imperfections concerning acceleration and deceleration (hence constant speed everywhere, except left and right edges).
So the challenge is not to break that.

On the other hand, I have noticed that the machine(s) I use are remarkably precise and seem very robust to speed changes (G0 vs G1). This is because I can cut difficult shapes. Cutting sometimes requires 20 or 30 repeat cycles to get trough 1 cm oak (for example) and the laser beam diameter is 0.01 mm ... So movement including speed changes is 0.01 mm precise, which I find incredible.

So, I will look into this. Don't expect me to complete this any time soon though.

**Comment by fdev31** [comment]
Yes, this one is relatively massive.
But I think it can be done incrementally... 
I didn't check the code details about this part, but a first (easy?) step would be to make this part of the code pluggable, so one could chose the current (default) behavior or ask to get the experimental mode.
In every case I think it would be wise to keep a "straightforward" version available for the following reasons:

- in case the "complex" algorithm fails in a specific case
- in case it's not worth or possible spending additional computing time (say it runs on a raspberry pi)

If I have time in the future I may be interested in experimenting with it and make some PRs.

**Comment by johannesnoordanus** [comment]
I have an update in the pipeline that includes most speedups you requested.
I am working on it.

**Comment by fdev31** [comment]
I'm currently testing it, it didn't finish but looks like it works like a charm :)
I believe I'm saving half of the time with my test image...
Just one remark, it looks like it implements the "crop to content" feature by default - to me it's an improvement but MAYBE some people will not like it.

**Comment by fdev31** [comment]
Looks like you implemented everything but the "ultimately" part. Amazing!
The last optimization (the real "flood fill" algorithm) is indeed quite complex, but maybe there are good reference algorithms or explanations.
The main advantage of it is for scenarios with outlines in almost empty shapes (think about an empty rectangle or circle). Also things like text etc... more or less every shape with a large "clear zone" vs "burned zone" ratio.
The code might not be ready for that, but maybe it's worth keeping it on the side and maybe refactor the code to make it possible (and maybe optional / keeping the current code as well) since this algorithm might be more slow... (and optimizing it a lot would probably lead to a lot more complexity). I can imagine some implementation and would give it a try eventually if I find my way with the code, but it would be very naive & slow I guess...

**Comment by johannesnoordanus** [comment]
I implemented all optimisation requests (except circular fill, because that is currently no option and won't be faster than 'flood fill' I think).
An added bonus is a speedmove option I added. This speeds the moves over non burn areas (empty pixels), when a distance is a certain size (for example 1cm) I did several tests and the result is (I don't like the word) 'amazing'.

You have to wait a little before I release it for svg2gcode.
I have a new implementation of image2gcode (version 2.0) that has every feature in it.
Good thing is that the algorithm and implementation is not much more (almost nothing) complex!

I think I will release a version of svg2gcode tomorrow.

(I am a bit puzzled what you tested yesterday, because I did not release anything yet!)

**Comment by fdev31** [comment]
Heh, I was probably using the git version on a venv.
I can't wait to test :)
I was playing a bit with the code & made a pull request with misc things inside, more on the "usability" / ux than performances so I don't think there will be any conflict :p
Anyway, all this sounds great :)

**Comment by fdev31** [comment]
I think the monochrome option is useless, it's like a slow PWM. I may do more tests... but not happy so far.

**Comment by johannesnoordanus** [comment]
Did a big update of svg2gcode (version 2.0.0 now). As mentioned above most request ar in.
I also updated image2gcode to version 2.1.0.
Enjoy!

**Comment by fdev31** [comment]
Great ! I'll probably do some tests over the weekend.

**Comment by johannesnoordanus** [comment]
I think this request is closed. You agree?

**Comment by fdev31** [comment]
Yes it's already much better.
I guess the real flood fill would not improve things that much in general
and it's also less kind regarding printer movements.
So to me it's good 👍🏽
